const express=require("express"),fetch=require("node-fetch"),path=require("path"),fs=require("fs"),{spawn}=require("child_process"),crypto=require("crypto");
const app=express();
app.use(express.json({limit:"20mb"}));
const API_KEY=process.env.ANTHROPIC_API_KEY,APP_PASSWORD=process.env.APP_PASSWORD||"changeme",PORT=process.env.PORT||3000;
if(!API_KEY)console.warn("WARNING: ANTHROPIC_API_KEY not set.");
function makeToken(pw){return crypto.createHmac("sha256",pw+"_fsj_2026").digest("hex");}
function isAuthed(req){const t=req.headers["x-session-token"]||req.query.token||"";return t===makeToken(APP_PASSWORD);}
app.get("/",(req,res)=>{if(isAuthed(req))return res.redirect("/app?token="+(req.query.token||makeToken(APP_PASSWORD)));res.send(LOGIN_PAGE);});
app.post("/auth",(req,res)=>{const{password}=req.body;if(password===APP_PASSWORD){res.json({ok:true,token:makeToken(APP_PASSWORD)});}else{res.status(401).json({ok:false,error:"Incorrect password"});}});
app.get("/app",(req,res)=>{if(!isAuthed(req))return res.redirect("/");const html=fs.readFileSync(path.join(__dirname,"app.html"),"utf8");const token=makeToken(APP_PASSWORD);const injected=html.replace("/* __SESSION_TOKEN__ */",`window.__SESSION_TOKEN__=${JSON.stringify(token)};`);res.send(injected);});
app.post("/api/claude",async(req,res)=>{if(!isAuthed(req))return res.status(401).json({error:"Unauthorized"});if(!API_KEY)return res.status(500).json({error:"API key not configured"});try{const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":API_KEY,"anthropic-version":"2023-06-01"},body:JSON.stringify(req.body)});const d=await r.json();if(!r.ok)return res.status(r.status).json(d);res.json(d);}catch(e){res.status(500).json({error:e.message});}});
app.post("/api/export",async(req,res)=>{if(!isAuthed(req))return res.status(401).json({error:"Unauthorized"});const py=spawn("python3",[path.join(__dirname,"export_xlsx.py")]);const chunks=[],errs=[];py.stdout.on("data",d=>chunks.push(d));py.stderr.on("data",d=>errs.push(d));py.stdin.write(JSON.stringify(req.body));py.stdin.end();py.on("close",code=>{if(code!==0)return res.status(500).json({error:Buffer.concat(errs).toString().slice(0,200)});res.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");res.setHeader("Content-Disposition",`attachment; filename="cashflow_${new Date().toISOString().slice(0,10)}.xlsx"`);res.send(Buffer.concat(chunks));});});
app.post("/api/export-pdf",async(req,res)=>{if(!isAuthed(req))return res.status(401).json({error:"Unauthorized"});const py=spawn("python3",[path.join(__dirname,"export_pdf.py")]);const chunks=[],errs=[];py.stdout.on("data",d=>chunks.push(d));py.stderr.on("data",d=>errs.push(d));py.stdin.write(JSON.stringify(req.body));py.stdin.end();py.on("close",code=>{if(code!==0)return res.status(500).json({error:Buffer.concat(errs).toString().slice(0,200)});res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",`attachment; filename="cashflow_${new Date().toISOString().slice(0,10)}.pdf"`);res.send(Buffer.concat(chunks));});});
app.post("/signout",(req,res)=>res.json({ok:true}));
app.get("/health",(req,res)=>res.json({ok:true}));
app.listen(PORT,()=>console.log(`Running on port ${PORT}`));
const LOGIN_PAGE=`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nonprofit Cash Flow Planner</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;600;700&display=swap" rel="stylesheet"><style>*{box-sizing:border-box;margin:0;padding:0;}body{font-family:'DM Sans',system-ui,sans-serif;background:#F5F5F5;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:1rem;}.box{background:#fff;border:1px solid rgba(0,0,0,.10);border-radius:14px;padding:2.5rem;width:100%;max-width:360px;box-shadow:0 4px 20px rgba(0,0,0,.08);}.logo{width:44px;height:44px;background:#1A1A1A;border-radius:10px;display:flex;align-items:center;justify-content:center;margin-bottom:1.25rem;}.logo svg{width:22px;height:22px;fill:none;stroke:#fff;stroke-width:2;}h1{font-size:20px;font-weight:700;margin-bottom:.25rem;}p{font-size:13px;color:#777;margin-bottom:1.5rem;}label{display:block;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.05em;color:#555;margin-bottom:5px;}input{width:100%;padding:10px 12px;border:1px solid #DDD;border-radius:8px;font-size:14px;font-family:inherit;outline:none;}input:focus{border-color:#555;}button{width:100%;margin-top:1rem;padding:11px;background:#1A1A1A;color:#fff;border:none;border-radius:8px;font-size:14px;font-weight:600;cursor:pointer;font-family:inherit;}button:hover{background:#333;}button:disabled{opacity:.5;}.err{color:#C0392B;font-size:13px;margin-top:.75rem;display:none;}.err.show{display:block;}</style></head><body><div class="box"><div class="logo"><svg viewBox="0 0 24 24"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg></div><h1>Nonprofit Cash Flow Planner</h1><p>Nonprofit Cash Flow Planner</p><label for="pw">Password</label><input type="password" id="pw" placeholder="••••••••" autofocus><button id="btn" onclick="login()">Sign in</button><div class="err" id="err">Incorrect password.</div></div><script>document.getElementById("pw").addEventListener("keydown",e=>{if(e.key==="Enter")login();});async function login(){const pw=document.getElementById("pw").value,btn=document.getElementById("btn"),err=document.getElementById("err");if(!pw)return;btn.disabled=true;btn.textContent="Signing in...";err.classList.remove("show");try{const r=await fetch("/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pw})});const d=await r.json();if(d.ok)window.location.href="/app?token="+d.token;else{err.classList.add("show");btn.disabled=false;btn.textContent="Sign in";}}catch(e){err.textContent="Connection error.";err.classList.add("show");btn.disabled=false;btn.textContent="Sign in";}}</script></body></html>`;
